spring:
  application:
    name: umc-bot

  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

discord:
  token: ${DISCORD_TOKEN}
  guild-id: ${DISCORD_GUILD_ID}

logging:
  level:
    net.dv8tion.jda: INFO